import numpy as np
import matplotlib.pyplot as plt

a_0 = np.array([258, 695, 961])
a_0e = np.array([74, 61, 162])
a_28 = np.array([323, 635, 910])
a_28e = np.array([72, 108, 109])
a_35 = np.array([422, 694, 976])
a_35e = np.array([68, 109, 106])

a_x = np.array([0, 280, 353])
a_xe = np.array([0, 0.35, 0.9])

lots_x = np.linspace(0,353,num=100)

plt.errorbar(a_x, a_0, yerr=a_0e, fmt='.k', ecolor='b', color = 'b')
a, b, c = np.polyfit(a_x, a_0, 2)
print(a)
print(b)
print(c)
plt.plot(lots_x,a*lots_x*lots_x + b*lots_x + c, c = 'c')
plt.xlabel("Height (mm)")
plt.ylabel("Velocity (um/s)")
plt.title("Velocity of Fluid at Various Heights Near Wall")
plt.legend(['Quadratic fit, a = 0.006, b = -0.092, c = 258', 'Data'], loc ="upper left")
plt.show()
plt.errorbar(a_x, a_28, yerr=a_28e, fmt='.k', ecolor='g', color = 'g')
a, b, c = np.polyfit(a_x, a_28, 2)
print(a)
print(b)
print(c)
plt.plot(lots_x,a*lots_x*lots_x + b*lots_x + c, c = 'c')
plt.xlabel("Height (mm)")
plt.ylabel("Velocity (um/s)")
plt.title("Velocity of Fluid at Various Heights Half Way Between Wall and Center of Channel")
plt.legend(['Quadratic fit, a = 0.008, b = -0.990, c = 323', 'Data'], loc ="upper left")
plt.show()
plt.errorbar(a_x, a_35, yerr=a_35e, fmt='.k', ecolor='r', color = 'r')
a, b, c = np.polyfit(a_x, a_35, 2)
print(a)
print(b)
print(c)
plt.plot(lots_x,a*lots_x*lots_x + b*lots_x + c, c = 'c')
plt.xlabel("Height (mm)")
plt.ylabel("Velocity (um/s)")
plt.title("Velocity of Fluid at Various Heights In Middle of Channel")
plt.legend(['Quadratic fit, a = 0.008, b = -1.32, c = 422', 'Data'], loc ="upper left")
plt.show()

# m, b = np.polyfit(a_x, a_0, 1)
# plt.plot(a_x, m*a_x + b, c = 'c')